services:
  receitasculinarias.db:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: receitasculinarias.db
    user: root
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_PASSWORD}
    volumes:
      - mssql-data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P \"${DB_PASSWORD}\" -Q \"SELECT 1\" || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  
  receitasculinarias.api:
    container_name: receitasculinarias.api
    build:
      context: .
      dockerfile: ReceitasCulinarias.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      # Configuração do banco de dados para apontar para o serviço 'db'
      - ConnectionStrings__DefaultConnection=Server=receitasculinarias.db,1433;Database=ReceitasCulinariasDb;User ID=sa;Password=${DB_PASSWORD};TrustServerCertificate=True;
      # Configurações do JWT (é melhor usar variáveis de ambiente)
      - Jwt__Key=${JWT_KEY}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
      - Jwt__DurationInMinutes=120
    depends_on:
      receitasculinarias.db:
        condition: service_healthy
  
  receitasculinarias.frontend:
    container_name: receitasculinarias.frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile

  nginx-proxy:
    container_name: nginx-proxy
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
    - receitasculinarias.api
    - receitasculinarias.frontend

volumes:
  mssql-data: